#! /usr/bin/env bash

# -*- mode: sh -*-
# vi: set ft=sh :

set -e

GIT_REPO=/home/codehero/codehero-repo.git
VENDOR=/home/codehero
TMP_GIT_CLONE=/home/codehero/tmp/repo
PUBLIC_WWW=/var/www/codehero-jekyll

BUNDLE="/usr/local/bin/bundle"

if [ -d  "$TMP_GIT_CLONE" ]; then
  echo "--------------> Removing old tmp builds"
  rm -Rf $TMP_GIT_CLONE
fi
echo "--------------> Cloning the repo"
git clone $GIT_REPO $TMP_GIT_CLONE
cd $TMP_GIT_CLONE &&\
  echo "--------------> Installing dependencies" &&\
  $BUNDLE install --path $VENDOR/vendor --deployment --without test --without development &&\
  $BUNDLE exec jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
echo "--------------> Application Deployed to $PUBLIC_WWW"
exit
